## Default values for Cloudflared

## @section Image parameters

## @param image.repository The Docker repository to pull the image from.
## @param image.tag The image tag to use.
## @param image.imagePullPolicy The logic of image pulling.
## @param image.arch Cpu Architecture.
##
image:
  repository: cloudflare/cloudflared
  imagePullPolicy: IfNotPresent

## If defined, uses a Secret to pull an image from a private Docker registry or repository
imagePullSecrets: []
## - name: test
## @param replicaCount The number of replicas to deploy.
##
replicaCount: 2
auth:
  tunnelToken: ""
## @param existingSecret The name of an existing secret containing the Argo tunnel settings.
##
existingSecret: ""
## @param nodeSelector stick pods to specifics nodes.
##
nodeSelector: 
