{{- if not .Values.existingSecret -}}
{{- if eq .Values.mode "tunnel" -}}
{{- if .Values.auth.tunnelToken }}
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-secret
type: Opaque
stringData:
  token: "{{ .Values.auth.tunnelToken }}"
{{- end }}
{{- else if eq .Values.mode "access" -}}
{{- if and .Values.auth.accessServiceTokenId .Values.auth.accessServiceTokenSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-secret
type: Opaque
stringData:
  serviceTokenId: "{{ .Values.auth.accessServiceTokenId }}"
  serviceTokenSecret: "{{ .Values.auth.accessServiceTokenSecret }}"
{{- end }}
{{- end }}
{{- end }}
