{{- if and (not .Values.existingSecret) .Values.auth.tunnelToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-secret
type: Opaque
stringData:
  token: "{{ .Values.auth.tunnelToken }}"
{{- end }}
